name: JavaScript workflow

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install, and test
        run: |
          npm install node-fetch
          node ec2.js
        env:
          CI: true
      - name: push
        run: |
           bash ./push
           echo "won"
        env:
            GITHUB_TOKEN: ${{ secrets.github_token }}
